name: ledger_scallop
description: A Flutter plugin to scan, connect & sign transactions using your Ledger devices
version: 1.0.0
homepage: https://developers.ledger.com/
repository: https://github.com/fum-is-chum/ledger
issue_tracker: https://github.com/fum-is-chum/ledger/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_reactive_ble:
    git:
      url: https://github.com/fum-is-chum/flutter_reactive_ble.git
      ref: master
      path: packages/flutter_reactive_ble
  protobuf: ^6.0.0
  ledger_usb: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  flutter_reactive_ble:
    git:
      url: https://github.com/fum-is-chum/flutter_reactive_ble.git
      ref: master
      path: packages/flutter_reactive_ble
  reactive_ble_mobile:
    git:
      url: https://github.com/fum-is-chum/flutter_reactive_ble.git
      ref: master
      path: packages/reactive_ble_mobile

flutter:
